version: '3'

services:
  # ------------------------------
  # Public containers
  # ------------------------------
  node:
    build: images/node
    environment:
      SERVER_PORT: 1080
      SERVER_HOST: 0.0.0.0
    volumes:
      - ../src:/app
    ports:
      - "1080:1080"

networks:
  private:
  brokerage:
  public: